import type { Vehicle, ChargingSchedule, HourlyDataPoint, ChargingSession } from '../types/wattwise';

export const INITIAL_VEHICLE: Vehicle = {
  id: 'veh_tm3_001',
  name: 'Srishti’s Model 3',
  model: 'Tesla Model 3',
  variant: 'Long Range Dual Motor',
  batteryCapacityKwh: 75,
  currentSoC: 62,
  targetSoC: 90,
  maxChargeRateKw: 11,
  chargerName: 'Wallbox Pulsar Plus',
  chargerType: 'Level 2 AC (3-Phase 16A)',
  vin: '5YJ3E1EB9MF892314',
  firmware: 'v2026.8.4',
  connected: true,
  status: 'scheduled',
};

export const INITIAL_SCHEDULE: ChargingSchedule = {
  connectTime: '6:30 PM',
  departureTime: '11:00 AM',
  connectDateTime: new Date('2026-09-12T18:30:00'),
  departureDateTime: new Date('2026-09-13T11:00:00'),
  flexibilityHours: 16,
  flexibilityMinutes: 30,
  optimalStart: '11:40 PM',
  optimalEnd: '2:10 AM',
  chargingDurationHours: 2.5,
  energyNeededKwh: 28.4,
  smartCost: 96,
  normalCost: 128,
  savings: 32,
  co2AvoidedKg: 4.2,
  normalCo2Kg: 7.3,
  smartCo2Kg: 3.1,
  isOptimizing: false,
  hasOptimized: true,
  chargeMode: 'smart',
};

// 24-hour hourly tariff and grid demand curve (6:00 PM to 12:00 PM next day)
export const HOURLY_ENERGY_DATA: HourlyDataPoint[] = [
  { hourLabel: '6 PM', rawHour: 18, tariff: 4.55, gridDemandGw: 4.9, renewablePercent: 36, isOptimal: false, isPluggedIn: true },
  { hourLabel: '7 PM', rawHour: 19, tariff: 4.70, gridDemandGw: 5.2, renewablePercent: 32, isOptimal: false, isPluggedIn: true },
  { hourLabel: '8 PM', rawHour: 20, tariff: 4.65, gridDemandGw: 5.0, renewablePercent: 34, isOptimal: false, isPluggedIn: true },
  { hourLabel: '9 PM', rawHour: 21, tariff: 4.40, gridDemandGw: 4.6, renewablePercent: 41, isOptimal: false, isPluggedIn: true },
  { hourLabel: '10 PM', rawHour: 22, tariff: 4.10, gridDemandGw: 3.8, renewablePercent: 49, isOptimal: false, isPluggedIn: true },
  { hourLabel: '11 PM', rawHour: 23, tariff: 3.65, gridDemandGw: 2.9, renewablePercent: 62, isOptimal: false, isPluggedIn: true },
  { hourLabel: '12 AM', rawHour: 0, tariff: 3.38, gridDemandGw: 1.8, renewablePercent: 79, isOptimal: true, isPluggedIn: true },
  { hourLabel: '1 AM', rawHour: 1, tariff: 3.35, gridDemandGw: 1.6, renewablePercent: 84, isOptimal: true, isPluggedIn: true },
  { hourLabel: '2 AM', rawHour: 2, tariff: 3.38, gridDemandGw: 1.7, renewablePercent: 81, isOptimal: true, isPluggedIn: true },
  { hourLabel: '3 AM', rawHour: 3, tariff: 3.42, gridDemandGw: 1.8, renewablePercent: 76, isOptimal: false, isPluggedIn: true },
  { hourLabel: '4 AM', rawHour: 4, tariff: 3.45, gridDemandGw: 2.0, renewablePercent: 72, isOptimal: false, isPluggedIn: true },
  { hourLabel: '5 AM', rawHour: 5, tariff: 3.55, gridDemandGw: 2.4, renewablePercent: 68, isOptimal: false, isPluggedIn: true },
  { hourLabel: '6 AM', rawHour: 6, tariff: 3.90, gridDemandGw: 3.2, renewablePercent: 55, isOptimal: false, isPluggedIn: true },
  { hourLabel: '7 AM', rawHour: 7, tariff: 4.25, gridDemandGw: 4.1, renewablePercent: 48, isOptimal: false, isPluggedIn: true },
  { hourLabel: '8 AM', rawHour: 8, tariff: 4.45, gridDemandGw: 4.7, renewablePercent: 45, isOptimal: false, isPluggedIn: true },
  { hourLabel: '9 AM', rawHour: 9, tariff: 4.35, gridDemandGw: 4.5, renewablePercent: 52, isOptimal: false, isPluggedIn: true },
  { hourLabel: '10 AM', rawHour: 10, tariff: 4.15, gridDemandGw: 4.2, renewablePercent: 64, isOptimal: false, isPluggedIn: true },
  { hourLabel: '11 AM', rawHour: 11, tariff: 3.95, gridDemandGw: 3.9, renewablePercent: 71, isOptimal: false, isPluggedIn: true },
  { hourLabel: '12 PM', rawHour: 12, tariff: 3.80, gridDemandGw: 3.6, renewablePercent: 78, isOptimal: false, isPluggedIn: false },
];

export const MOCK_HISTORY_SESSIONS: ChargingSession[] = [
  {
    id: 'ses_001',
    date: 'Yesterday, Sep 11',
    timeRange: '12:10 AM — 2:25 AM',
    energyKwh: 24.2,
    cost: 82,
    normalCost: 110,
    savings: 28,
    co2AvoidedKg: 3.6,
    targetReached: 85,
    isOptimal: true,
    charger: 'Wallbox Pulsar Plus (Home)',
  },
  {
    id: 'ses_002',
    date: 'Tuesday, Sep 09',
    timeRange: '11:45 PM — 2:40 AM',
    energyKwh: 31.0,
    cost: 105,
    normalCost: 142,
    savings: 37,
    co2AvoidedKg: 4.8,
    targetReached: 90,
    isOptimal: true,
    charger: 'Wallbox Pulsar Plus (Home)',
  },
  {
    id: 'ses_003',
    date: 'Sunday, Sep 07',
    timeRange: '1:15 AM — 3:00 AM',
    energyKwh: 19.5,
    cost: 66,
    normalCost: 89,
    savings: 23,
    co2AvoidedKg: 2.9,
    targetReached: 80,
    isOptimal: true,
    charger: 'Wallbox Pulsar Plus (Home)',
  },
  {
    id: 'ses_004',
    date: 'Friday, Sep 05',
    timeRange: '11:30 PM — 2:50 AM',
    energyKwh: 35.8,
    cost: 121,
    normalCost: 164,
    savings: 43,
    co2AvoidedKg: 5.5,
    targetReached: 95,
    isOptimal: true,
    charger: 'Wallbox Pulsar Plus (Home)',
  },
  {
    id: 'ses_005',
    date: 'Tuesday, Sep 02',
    timeRange: '12:00 AM — 2:20 AM',
    energyKwh: 26.4,
    cost: 89,
    normalCost: 119,
    savings: 30,
    co2AvoidedKg: 3.9,
    targetReached: 90,
    isOptimal: true,
    charger: 'Wallbox Pulsar Plus (Home)',
  },
];
